const CLOUD = "https://res.cloudinary.com/dhbmaw1bm/image/upload/w_2500,q_auto,f_auto";
// const CLOUD = "https://res.cloudinary.com/dhbmaw1bm/image/upload";
const CLOUD_THUMB = "https://res.cloudinary.com/dhbmaw1bm/image/upload/w_800,q_auto,f_auto";



const photos = {
  nippon: [
    { id: "IMGL9507-2_v7b1qi", alt: "Temple japonais sous la neige, Kyoto" },
    "IMGL9507-2_v7b1qi",
    "IMGL9125_xi2v8p",
    "IMGL9022-2_rkc5iz",
    "IMGL9290_qkl7ms",
    "IMGL9455-2_k2gf4n",
    "IMGL8016_abso7v",
    "IMGL7076_bvbf8d",
    "IMGL7079-2_wygdzy",
    "IMGL7085-2_vslaft",
    "IMGL7133-2_mwzhwz",
    "IMGL6308_m3wdzf",
    "IMGL6361-2_impjst",
    "IMGL6308_m3wdzf",
    "IMGL6401_t0sgu3",
    "IMGL6361_o04q0l",
    "IMGL6361_o04q0l",
    "IMGL6308-2_dfy8bp",
    "633A6188_fc5h7j",
    "633A5834_qxhjbb",
    "633A5836_l1cr8y",
    "633A5935-2_r1itex",
    "633A5342-2_oyh2vn",
    "633A5350_mnpc5c",
    "633A3955_fbaer4",
    "633A2655_rjyv6d",
    "633A4353_rvbrzi",
    "633A2100_zv9vi1",
    "633A2315_sylxvg",
    "633A2332_tieznu",
    "633A2670_lifeof",
    "633A2647_da8bf9",
    "v1767280805/IMGL1205_ekhgm3.jpg",
    "633A2876-2_ijjdyz",
    "633A2291_kzpht8",
    "633A2332_tieznu",
    "633A2670_lifeof",
    "633A2633_hsprzi",
    "633A2947-3_ipnlh1",
    "633A2948_dbigqw",
    "633A2823_yi1gyn",
    "633A2801-2_ehmumd",
    "633A2791_nrly1v",
    "633A2742_hbcanb",
    "633A2678_gdmuxc",
    "633A9782_snev9q",
    "633A9750-2_v9yu1p",
    "633A9737_htbmdo",
    "633A9774_lncvuz",
    "IMGL7139-2_evavfp", //buddha//

   
  ],
  city: [
   "IMGL0052_kadhr6",
   "IMGL0155_bbacvq",
   "IMGL0244_szszux",
   "IMGL0110_sffxzc",
   "IMGL0053_ebnt2j",
   "IMGL0222-2_vyemrc",
   "IMGL0683_g6hobz",
   "IMGL0600_gq3rui",
   "633A4201-2_ccpn6k",
   "633A0719-2_myeinr",
   "633A1962_gghy9r",
   "IMGL6869_loq8ks",
   "IMGL2213-2_znhicb",
   "IMGL0366_kiseoq",
   "633A0787-2_bfnm8s",
   "IMGL0022_ng44nl",
   "IMGL6486_nm9ria",
   "IMGL6479_gh4r3j",
   "IMGL6508-2_ht6599",
   "IMGL0222-2_q6lsou",
   "IMGL2289-3_yqhrcf",
   "IMGL0102_is13up",
   "633A0668_zirvu8",
   "IMGL0106_znfah4",
   "IMGL6734_hcar2g",
   "633A4107_uu4baf",
   "IMGL0135_n59qbt",
   "IMGL6503-5_idx04h",
   "IMGL6479-2_d7wk4f",
   "IMGL2282_wdmhql",
   "IMGL0030_ffyepo",
   "IMGL6479_gh4r3j",
   "633A0545-3_tbwbtu",
   "IMGL0023_jls22d",
  


  

  ],

  animals: [
   "IMGL9574_yyfs0p",
   "IMGL9573_jkhaxs",
   "IMGL9617-6_iirn6r",
   "IMGL9617-3_znzcpm",
   "IMGL9611-7_icvtgj",
   "IMGL1824-4_ff1nic",
   "IMGL1877-2_q2sw5t",
   "IMGL1874_ffzmwk",
   "IMGL1877-2_q2sw5t",
     "633A4646_pxyvi9",
    "633A4645_p2vyfe",
    "633A4851_ucuix0",
    "633A4773_koghen",
    "IMGL6576-2_zbyfji",
    "633A4052_cuq4jg",
    "633A0337_lzgtym",
    "633A0381-2_ojc6ke",
    "633A0355-3_kmm3qa",
    "IMGL0323_n4nfkw",
    "IMGL7735-2_t432k3",
    "IMGL7794-2_ok8p7s",
    "IMGL7686_mvc54s",
    "IMGL7735_ktld6j",
    "IMGL7803-2_tchn2m",
    "IMGL7721_ngwgda",
    "IMGL7696_l4bck2",
    "IMGL7687_gafpn0",
    "IMGL7697_ofxpom",
    "IMGL7720_zhmoz1",
    "IMGL7792-2_eycgbc",
    "633A4056_b6qkuo",
    "IMGL7735-2_t432k3",
    "633A0355-5_v9jirb",
    "633A4773_koghen",
    "IMGL0904_qcfgko",
    "MGL0899_kdca9a",
    "IMGL0058-2_fs8vii",
    "IMGL0717_rz16j9",
    "IMGL0058_f7wsy8",
    "IMGL0899-2_aukoso",
    "IMGL0173-2_krrrqt",
    "IMGL0720_p9tm35",
    { id: "IMGL0720_p9tm35", alt: "Heron, Kyoto" },
    "IMGL0222_evahkk",
    "IMGL0145-2-2_tx4r8d",
    "IMGL0760_nz9tav",


  

  ],

    blackwhite: [
    "v1767280805/IMGL1205_ekhgm3.jpg",
    "IMGL0084_ttuta6",
    "IMGL9617-7_qymeu0",
    "IMGL7785_shac7l",
    "IMGL6653_be7igj",
    "IMGL6648_pvlcjd",
    "IMGL6647_g29lkh",
    "IMGL6508-3_ouclo0",
    "633A4646_pxyvi9",
    "633A4645_p2vyfe",
    "633A4056_kxx1kr",
    "633A2876-2_ijjdyz",
    "633A2819-2_phpifn",
    "633A9747_xc6jb3",
    "633A9668_dkksrt",
    "633A9668_dkksrt",
    "633A8526_hhzmsl",
    "633A8526_hhzmsl",
    "633A8262-2_om5rzu",
    "633A8255_fqbvfv",
    "633A8154_ggv7bg",
    "IMGL6671_slrzx3",
    "IMGL6649_hhaf0m",
    "IMGL9865-2_fplmno",
    "IMGL6734-2_yjuhti",
    "IMGL7687_gafpn0",
    "IMGL7697_ofxpom",
    "IMGL7792-2_eycgbc",
    "633A4056_b6qkuo",
    "IMGL7735-2_t432k3",
    "IMGL1615_xmmjsw",
    "IMGL1809_edjx8h",
    "IMGL2022_tpky3d",
    "IMGL2021_exwys6",
    "IMGL1687-4_l5ql0l",
    "IMGL1805_ylvhnc",
    "IMGL5907_enbs3m",
    "IMGL1574-3_v9zama",
    "IMGL1788-2_vgddv1",
    "IMGL0323_n4nfkw",


  

  ],

 rouge: [
  "IMGL7133-2_mwzhwz",
  "633A5342-2_oyh2vn",
  "IMGL7076_bvbf8d",
  "IMGL7079-2_wygdzy",
  "IMGL9125_xi2v8p",
  "IMGL6361-2_impjst",
  "633A9737_htbmdo",
  "IMGL9507-2_v7b1qi",
  "IMGL9290_qkl7ms",
  "633A6188_fc5h7j",
  "633A5834_qxhjbb",
  "IMGL6401_t0sgu3",
  "IMGL7034-4_axplpr",
  "633A5350_mnpc5c",
  "IMGL6794_bygzlw",
  "633A5935-2_r1itex",
  "633A0381-2_ojc6ke",
  "633A0337_lzgtym",
  "633A5350_mnpc5c",
  { id: "IMGL8467_luqxmg", alt: "Red torii gate in autumn foliage", description: "Explore the serene beauty of a Kyoto temple torii gate surrounded by vibrant fall foliage. Capture stunning travel photography with this iconic landmark." },
  { id: "IMGL9823_cra6rl", alt: "Bright red torii gate and bridge in autumnal setting", description: "Explore the vibrant colors of a Kyoto torii gate and bridge during fall, capturing serene Japanese architecture amidst lush foliage." },
  { id: "IMGL9709_zlasps", alt: "Traditional Japanese shrine gate with red and orange accents on a cloudy day", description: "Explore the serene beauty of a traditional Japanese shrine gate under a cloudy sky. This iconic red pagoda stands as a symbol of cultural heritage in Kyoto, Japan." },
  "IMGL6382-2_mm82yc",
 

 ],

 rose: [
  { id: "633A7585-3_rwbjox", alt: "Ferris wheel and roller coaster at an amusement park with a clear sky", description: "Explore the vibrant world of amusement parks! This image captures the iconic ferris wheel and thrilling roller coaster under a bright blue sky, perfect for thrill-seekers and families alike." },

 ],

 bleu: [
  { id: "sunburst_cloudscape", alt: "Sunbeams piercing through dramatic cloudscape with soft lighting", description: "Explore the beauty of a sunburst breaking through dense cloud cover in this stunning landscape photo. Perfect for nature and travel enthusiasts." },
  { id: "kyoto_sunset_autumn", alt: "Kyoto sunset over autumnal hills and traditional rooftops", description: "Experience the serene beauty of Kyoto at sunset with stunning views of autumn foliage and traditional Japanese rooftops. Capture the essence of Japan's cultural heritage in this breathtaking shot." },
  { id: "kyoto_sunset_dramatic", alt: "Sunbeams piercing through clouds over a mountainous landscape", description: "Capture the breathtaking view of Kyoto at sunrise with stunning sunbeams and clouds. Explore Japanese architecture in this travel photography portfolio." },
  { id: "ferris_wheel_amusement_park", alt: "ferris wheel and roller coaster under a blue sky", description: "Explore the thrill of an amusement park with this stunning shot featuring a towering ferris wheel and vibrant red roller coaster against a clear blue sky. Perfect for travel photography enthusiasts!" },
  { id: "castle_moat_sunset", alt: "Sunset reflection in moat at historical castle gate", description: "Explore the serene beauty of a historic castle's moat at sunset. Capture stunning reflections and architectural details." },
  { id: "sunset_over_japanese_architecture", alt: "serene sunset over traditional Japanese architecture and mountains", description: "Experience the tranquil beauty of a serene sunset overlooking traditional Japanese architecture and stunning mountain views. Capture this moment in your travel photography portfolio." },
  
 { id: "IMGL8169-2_hnin0q", alt: "Red and orange tower against deep blue sky", description: "Explore the vibrant red and orange hues of this striking architectural structure set against a stunning deep blue sky. A must-see for photography enthusiasts!" },
 { id: "IMGL3226_eyhiiz", alt: "Red pagoda temple in Kyoto under a clear blue sky", description: "Explore the serene beauty of Kyoto's iconic red pagoda temple, captured against a stunning clear blue sky. This stunning travel photography showcases traditional Japanese architecture and vibrant colors." },
 "633A2647_da8bf9",
 "633A2655_rjyv6d",
 { id: "IMGL2919_wva2bb", alt: "Kiyomizu-dera Temple in Kyoto, Japan", description: "Explore the serene beauty of the Kiyomizu-dera Temple in Kyoto, Japan. This stunning red pagoda stands majestically against a clear blue sky." },
 { id: "IMGL8067_e1tzwg", alt: "Kyoto's Kiyomizu-dera Temple against a clear blue sky", description: "Explore the stunning red and green rooflines of Kyoto's iconic Kiyomizu-dera Temple under a vibrant blue sky. Experience Japanese architecture at its finest!" },
 { id: "IMGL3061_qwqvlh", alt: "Kyoto's Kiyomizu-dera Temple under a clear blue sky", description: "Explore the stunning Kiyomizu-dera Temple, showcasing its iconic red pagoda against a vivid blue sky. Capture the essence of Japanese architecture and culture." },
 { id: "IMGL7265_ftcldl", alt: "Sunbeams through clouds over mountainous landscape", description: "Explore breathtaking sunbeams piercing through dramatic clouds over a stunning mountainous landscape. This unique travel photo captures the essence of nature's beauty." },
 { id: "IMGL6741_yi1yeo", alt: "Giant statue of Guanyin under a clear blue sky", description: "Explore the serene beauty of a giant Guanyin statue bathed in morning light, set against a clear blue sky. This stunning photograph captures the spiritual essence and architectural grandeur of this iconic landmark." },
 { id: "633A7585_tj66gm", alt: "ferris wheel and roller coaster against a blue sky", description: "Explore the thrill of an amusement park with this stunning shot featuring a Ferris wheel and roller coaster under a clear blue sky. Perfect for travel enthusiasts seeking adventure photography inspiration." },
 { id: "633A7552_e1mfnw", alt: "Ferris wheel against a cloudy sky with roller coaster in foreground", description: "Explore the vibrant amusement park scene featuring a giant Ferris wheel and roller coaster under a dramatic cloudy sky. A must-see for travel photography enthusiasts!" },
 { id: "IMGL7602_gwyged", alt: "Kyoto cityscape with autumn leaves and full moon", description: "Experience the serene beauty of Kyoto's cityscape at sunset. This stunning photo captures the vibrant autumn foliage, traditional architecture, and a full moon rising over the mountains." },
 { id: "IMGL7584_inet1k", alt: "Reflections in a moat at dusk with castle walls and trees", description: "Explore the serene beauty of a historic castle's moat at dusk, capturing reflections that mirror the dramatic sky. Discover more travel photography from Thomas (Ashtar Fox) across various locations." },
 { id: "633A7552-2_g3ijdg", alt: "Ferris wheel at an amusement park under a cloudy sky", description: "Explore the vibrant scene of a giant Ferris wheel against a dramatic cloudy sky in this stunning travel photograph." },
 { id: "633A7602_ucktyp", alt: "cosmo world ferris wheel at sunset", description: "Explore the vibrant Cosmo World Ferris Wheel in this stunning sunset travel photo. Capture the magic of this iconic landmark with our high-resolution images." },
 { id: "633A7171_phsgma", alt: "Traditional Japanese sake barrels with whale design", description: "Explore the intricate artistry of traditional Japanese sake barrels adorned with a striking whale design. This unique photo captures the cultural heritage and craftsmanship behind these iconic containers." },
 { id: "633A7585-3_rwbjox", alt: "Ferris wheel and roller coaster at an amusement park with a clear sky", description: "Explore the vibrant world of amusement parks! This image captures the iconic ferris wheel and thrilling roller coaster under a bright blue sky, perfect for thrill-seekers and families alike." },
 { id: "IMGL7265-2_zzx3qa", alt: "Dramatic cloudscape with sunbeams over a mountainous landscape", description: "Explore the breathtaking beauty of a mountainous region where sunlight pierces dramatic cloud formations, creating a stunning natural spectacle." },
 { id: "633A0588_endkhl", alt: "A giant Earth globe suspended in a modern building with glass walls and ceiling lights.", description: "Explore the stunning interior of a contemporary building featuring an enormous Earth globe hanging from the ceiling, perfect for travelers interested in architecture and unique design elements." },
 { id: "633A0588_endkhl", alt: "A giant Earth globe suspended in a modern building with glass walls and ceiling lights.", description: "Explore the stunning interior of a contemporary building featuring an enormous Earth globe hanging from the ceiling, perfect for travelers interested in architecture and unique design elements." },
{ id: "IMGL7596_pnsigi", alt: "serene temple complex at twilight with dramatic sky", description: "Explore the tranquil beauty of a temple complex at twilight, featuring stunning architecture and a majestic sky. Experience the serenity of this iconic location." },
"633A2670_xtiqs1",
"633A2633_nmlayg",
"633A2679_kg2d7p",
"633A2655_ri31ji",
"633A2540_x5ybgf",
"633A2581_tkrkwh",


 ],

 orange: [
  { id: "kiyomizu_dera_roof_2", alt: "Red pagoda roof against Kyoto cityscape under blue sky", description: "Explore the stunning red pagoda of Kiyomizu-dera temple, its vibrant colors contrasting with the serene backdrop of Kyoto's city skyline and clear winter skies." },
  { id: "torii_gate_autumn", alt: "Red torii gate framed by bare branches in Kyoto, Japan", description: "Explore the serene beauty of a red torii gate in Kyoto, Japan. Captured from an intriguing angle with bare tree branches framing the scene." },
  { id: "lighthouse_twilight", alt: "Red monument against a deep blue sky", description: "Explore the striking contrast of a vibrant red monument set against an inky-blue sky, capturing the essence of architectural beauty and dramatic lighting." },
  { id: "autumn_torii_shrine", alt: "A red torii gate leading to a traditional Japanese shrine surrounded by autumn foliage.", description: "Explore the serene beauty of an autumnal Japanese shrine, featuring a striking red torii gate and traditional architecture amidst vibrant fall colors. Perfect for travel photography enthusiasts." },
  { id: "japanese_temple_roof_2", alt: "Fushimi Inari Shrine's iconic red torii gates against a blue sky", description: "Explore the vibrant red torii gates of Fushimi Inari Shrine in Kyoto, Japan. This stunning photograph captures the spiritual beauty and architectural splendor of this iconic landmark." },
  { id: "japanese_pagoda_blue_sky", alt: "Kyoto's Kiyomizu-dera Temple Pagoda under a clear blue sky", description: "Explore the stunning architecture of Kyoto’s iconic Kiyomizu-dera Temple Pagoda, captured in breathtaking morning light against a vibrant blue sky. This photo is perfect for travelers seeking Japanese temple photography inspiration." },
  { id: "japanese_pavilion_red", alt: "Red pagoda in Kyoto temple complex under clear blue sky", description: "Explore the serene beauty of a red-roofed pagoda in Kyoto's ancient temple complex, captured on a crisp winter day with vibrant colors and stunning architecture." },
  { id: "japanese_shrine_red_torii", alt: "Red torii gate leading to a traditional Japanese shrine in autumn foliage.", description: "Explore the serene beauty of Kyoto's red torii gates amidst vibrant autumn leaves. This stunning travel photo captures the essence of Japan's ancient shrines and seasonal landscapes." },
  { id: "torii_gate_twilight", alt: "Red torii gate against a deep blue sky in Japan", description: "Explore the vibrant red torii gates of Kyoto, Japan. Captured from an unusual angle with dramatic lighting and deep blue skies." },
  { id: "pagoda_red_sky", alt: "Red pagoda against a vibrant blue sky in Kyoto", description: "Explore the stunning red pagoda of Kyoto, captured from an innovative angle under a vivid blue sky. This iconic Japanese landmark is a must-see for travelers and photography enthusiasts." },
  { id: "kiyomizu_dera_roof", alt: "Kyoto temple roof against a clear blue sky", description: "Explore the stunning contrast of Kyoto's iconic red temple roof set against a vibrant blue sky, capturing the essence of Japanese architecture in this serene cityscape." },
  { id: "kiyomizu_dera_pagoda_winter", alt: "Bright red pagoda against a clear blue sky in Kyoto.", description: "Explore the stunning red pagoda of Kyoto, Japan, captured under a vibrant blue sky. This iconic temple is a must-see for travelers and photography enthusiasts alike." },
  { id: "japanese_shrine_red_torii_3", alt: "Red torii gate and bridge over stream in Kyoto temple complex", description: "Explore the serene beauty of a famous Japanese temple featuring vibrant red torii gates, a stone bridge, and a tranquil stream. Perfect for travel photography enthusiasts." },
  { id: "traditional_temple_bright_sky", alt: "Traditional Japanese temple with vibrant red and green architecture against a clear blue sky.", description: "Explore the stunning architectural details of a Kyoto temple, featuring its iconic red pagoda set against a vivid blue sky. This photograph captures the serene beauty of traditional Japanese architecture." },
  { id: "pagoda_vivid_red", alt: "Bright red pagoda against a clear blue sky in Kyoto", description: "Explore the vibrant red roof of an iconic Kyoto pagoda under a stunning clear blue sky. This unique angle captures the essence of Japanese architecture and cultural beauty." },
  { id: "japan_torii_gate", alt: "Red torii gate leading to a Japanese shrine on a cloudy day.", description: "Explore the serene beauty of Kyoto's iconic red torii gate, captured under morning clouds. A must-see for travelers exploring Japan's temples and shrines." },
  { id: "japanese_shrine_red_torii_4", alt: "Kyoto temple with red torii gate and stone bridge", description: "Explore the serene beauty of Kyoto's iconic temples, featuring a striking red torii gate and traditional stone bridge. This picturesque scene captures the essence of Japanese architecture and tranquility." },
  { id: "kiyomizu_dera_pagoda_vibrant", alt: "Traditional Japanese temple roof against a clear blue sky", description: "Explore the serene beauty of Kyoto's iconic temples captured in stunning morning light. Experience the majesty and history of Japan’s ancient architecture." },
  { id: "japanese_pagoda_evening", alt: "Bright red pagoda against a clear blue sky, Kiyomizu-dera Temple in Kyoto", description: "Explore the iconic red pagoda of Kiyomizu-dera temple in Kyoto, Japan. Captured with dramatic lighting and stunning architecture." },
  { id: "pagoda_roof_details", alt: "Traditional Japanese temple architecture under a clear blue sky", description: "Explore the intricate roof details of Kyoto's iconic temples during winter, capturing the vibrant red and gold hues against a crisp blue sky." },
  { id: "kyoto_red_torii_sunset", alt: "Red torii gate overlooking Kyoto cityscape", description: "Explore the vibrant red torii gate of Kyoto's Fushimi Inari Shrine during a stunning sunset, capturing the iconic Japanese landmark in all its glory." },
  { id: "kiyomizu_dera_pagoda_10", alt: "Kyoto's Fushimi Inari Shrine under a clear blue sky", description: "Explore the vibrant red pagodas of Fushimi Inari Shrine in Kyoto, Japan. Capture stunning architecture against a brilliant blue sky." },
  { id: "red_pagoda_sky", alt: "Detailed view of a vibrant red pagoda against a clear blue sky.", description: "Explore the intricate details and vibrant colors of this iconic Kyoto pagoda under a clear blue sky, perfect for travel photography enthusiasts." },
  { id: "japanese_temple_roof", alt: "Red pagoda of Kiyomizu-dera Temple in Kyoto under a clear blue sky", description: "Explore the iconic red pagoda at Kiyomizu-dera Temple in Kyoto, Japan. Capture stunning architecture against a vibrant blue sky." },
  { id: "kiyomizu_dera_pagoda_11", alt: "Traditional Japanese temple architecture under a vibrant blue sky", description: "Explore the stunning red pagoda architecture of Kyoto, Japan. This captivating travel photo captures the intricate details and vibrant colors against a clear blue sky." },
  { id: "kiyomizu_dera_pagoda_2", alt: "Bright red pagoda under a clear blue sky", description: "Explore the vibrant beauty of Kyoto's iconic red pagoda against a stunning clear blue sky. Capture the essence of Japanese architecture in this stunning travel photography shot." },
  { id: "kiyomizu_dera_pagoda_autumn", alt: "Kyoto's Kiyomizu-dera Temple on a clear day", description: "Experience the vibrant colors and serene atmosphere of Kyoto’s iconic Kiyomizu-dera Temple captured during a stunning sunrise." },
  { id: "kiyomizu_dera_pagoda_4", alt: "Bright red pagoda against a blue sky in Kyoto", description: "Explore the vibrant beauty of Kyoto's iconic red pagoda set against a stunning blue sky, capturing its serene and majestic atmosphere." },
  { id: "kiyomizu_dera_pagoda_5", alt: "Bright red pagoda against a clear blue sky", description: "Experience the vibrant beauty of Kyoto's iconic red pagoda set against a stunning blue sky, capturing the essence of Japanese architecture and serene atmosphere." },
  { id: "kiyomizu_dera_pagoda_7", alt: "Bright red pagoda against a clear blue sky in Japan", description: "Explore the vibrant red pagoda of Kyoto, Japan, captured from an elevated angle under a brilliant blue sky. A stunning travel photography shot that highlights Japanese architecture." },
  { id: "kiyomizu_dera_pagoda_6", alt: "Brightly colored pagoda against a clear blue sky", description: "Explore the vibrant beauty of Kyoto's iconic pagoda under winter sunlight, capturing its intricate architecture and striking red hues." },
  
 "633A5834_qxhjbb", 
 "IMGL8016_abso7v",
 { id: "IMGL8169-2_hnin0q", alt: "Red and orange tower against deep blue sky", description: "Explore the vibrant red and orange hues of this striking architectural structure set against a stunning deep blue sky. A must-see for photography enthusiasts!" },
 { id: "IMGL3056_rj8gsi", alt: "Bright red pagoda against a clear blue sky", description: "Explore the stunning winter view of Kyoto's iconic Kiyomizu-dera temple, featuring its vibrant red pagoda and intricate architecture under a crisp blue sky." },
 { id: "IMGL8089_oefz9i", alt: "Vibrant orange pagoda against a clear blue sky", description: "Explore the stunning architecture of Kyoto's iconic temple, captured from a unique angle with vibrant orange roofs and a clear blue sky backdrop." },
 { id: "IMGL2981_cq2una", alt: "Kiyomizu-dera Temple in Kyoto, Japan", description: "Explore the iconic red pagoda of Kiyomizu-dera Temple in Kyoto, Japan. This stunning angle captures the vibrant architecture against a clear blue sky." },
 { id: "IMGL3061_qwqvlh", alt: "Kyoto's Kiyomizu-dera Temple under a clear blue sky", description: "Explore the stunning Kiyomizu-dera Temple, showcasing its iconic red pagoda against a vivid blue sky. Capture the essence of Japanese architecture and culture." },
 { id: "IMGL2981-2_efhcop", alt: "Bright red pagoda under a clear blue sky", description: "Explore the vibrant red pagoda of Kyoto's famous temple, captured from an unique angle against a crisp blue sky. A must-see for travel photography enthusiasts." },
 { id: "IMGL3226_eyhiiz", alt: "Red pagoda temple in Kyoto under a clear blue sky", description: "Explore the serene beauty of Kyoto's iconic red pagoda temple, captured against a stunning clear blue sky. This stunning travel photography showcases traditional Japanese architecture and vibrant colors." },
 { id: "IMGL2919_wva2bb", alt: "Kiyomizu-dera Temple in Kyoto, Japan", description: "Explore the serene beauty of the Kiyomizu-dera Temple in Kyoto, Japan. This stunning red pagoda stands majestically against a clear blue sky." },
 { id: "IMGL3231_mradbm", alt: "Bright red pagoda structure against a clear blue sky", description: "Explore the vibrant beauty of Kyoto's iconic red pagodas under a stunning blue sky. This photograph captures the essence of traditional Japanese architecture in its finest detail." },
 { id: "IMGL8067_e1tzwg", alt: "Kyoto's Kiyomizu-dera Temple against a clear blue sky", description: "Explore the stunning red and green rooflines of Kyoto's iconic Kiyomizu-dera Temple under a vibrant blue sky. Experience Japanese architecture at its finest!" },
 { id: "IMGL2942-4_yp62kf", alt: "Red pagoda of Kiyomizu-dera Temple in Kyoto under a clear blue sky", description: "Discover the stunning red pagoda at Kiyomizu-dera, Kyoto's iconic temple. Capture its vibrant hues and serene atmosphere." },
 "IMGL9413-2-3_xaon44",
 "IMGL9413-2-3_xaon44",
 { id: "IMGL9801_davkrw", alt: "A couple walks under an umbrella in front of a vibrant red pagoda temple on a cloudy day.", description: "Explore the serene beauty of Kyoto's iconic red pagoda temples with this stunning travel photography. Capture the essence of Japanese architecture and cultural heritage in one frame." },
 { id: "IMGL9801_davkrw", alt: "A couple walks under an umbrella in front of a vibrant red pagoda temple on a cloudy day.", description: "Explore the serene beauty of Kyoto's iconic red pagoda temples with this stunning travel photography. Capture the essence of Japanese architecture and cultural heritage in one frame." },
 { id: "IMGL9734_ztvbwg", alt: "Red torii gate and bridge at Fushimi Inari Shrine in Kyoto", description: "Explore the iconic red torii gates of Fushimi Inari Shrine, captured from a unique angle with dramatic lighting. A must-see for anyone visiting Japan's spiritual heart." },
 { id: "IMGL2813_p81pdx", alt: "Japanese temple with red pagoda and Japanese flag against a blue sky", description: "Explore the serene beauty of Kyoto's iconic temples, featuring vibrant red pagodas and the Japanese flag fluttering in the breeze." },
 { id: "IMGL9798_ubh1vs", alt: "Red torii gate and pagoda at Fushimi Inari Shrine in Kyoto", description: "Explore the iconic red torii gates of Fushimi Inari Shrine, a stunning temple complex in Kyoto, Japan. Capture the vibrant colors and serene atmosphere with your camera." },
 { id: "IMGL0547-2_asqlld", alt: "Red torii gate at Fushimi Inari Shrine in Kyoto, Japan", description: "Explore the iconic red torii gates of Fushimi Inari Shrine in Kyoto, Japan. Captured with precision and beauty by Ashtar Fox." },
 { id: "IMGL8454_dcgz6s", alt: "Red torii gate and traditional Japanese temple in autumn foliage", description: "Explore the serene beauty of a Kyoto temple during autumn, featuring vibrant red torii gates and traditional architecture amidst golden foliage." },
 { id: "IMGL9823_cra6rl", alt: "Bright red torii gate and bridge in autumnal setting", description: "Explore the vibrant colors of a Kyoto torii gate and bridge during fall, capturing serene Japanese architecture amidst lush foliage." },
 { id: "IMGL2765_gei45w", alt: "Kyoto's Kiyomizu-dera Temple under a dramatic sky", description: "Explore the stunning red pagoda of Kiyomizu-dera temple in Kyoto, Japan. This iconic landmark is set against a backdrop of lush greenery and a dynamic blue sky with clouds." },
 

 ],
  
vert: [
  
 "633A4773_koghen",
 "633A2801-2_ehmumd",
 "633A8875-2_zzr88o",
 "633A8066_slrnfe",
 "633A5635_bxjnci",
 "633A5543_ww7k8e",
 "633A5540-2_wvro56",
 "633A7197_urzwqh",
 "633A5637_acebts",
 "633A8117_kwymyf",
 "633A7185_mgt0x5",
 "633A2771_lthfsz",
 "633A2791-2_rngryh",
 "633A2812_g3fo2u",
 "633A9371_brrzmw",
 "633A5571_d2uocd",
 "633A5572_iptyzp",
 "633A2801-2_o6r6m9",
 "633A8147_uxi4q7",
 "633A8151_n0xybu",



 ],
jaune: [
  "IMGL7139_jdirjl",
  "633A8955_hiefub",
  "633A4997_xezelb",
  "633A0563_g9uvgm",
  "IMGL7143_wb18ym",
  "IMGL6924_ydjow4",
  "IMGL7145_ra40lh",
  "IMGL0600_brdbbl",
  "IMGL7142_lchheg",
  "633A8544_mwwa8n",
  "IMGL6711_rifu1c",
  "IMGL6924_ydjow4",
  "IMGL0600_brdbbl",
  "633A0381-2_ojc6ke",
  
 



 ],
 bynight: [
  
"633A4201-2_ccpn6k",
"IMGL6391_fyjyxc",
"IMGL6233_ty24q5",
"IMGL6382-2_mm82yc",
"IMGL6302_r9rbyi",
"633A5312_oikwmo",
"IMGL6227-5_mgwxwc",
"633A0505_qmrxzk",
"IMGL0296_joeng5",
"IMGL6302-2_owzop7",
"633A0442_kvknxc",
"IMGL6229_c7x8hc",
"633A8435_rgwvrv",
"633A4198_x7ldor",
"IMGL0312_xqjqd3",
"633A4181_glesvk",
"633A0461-2_qxbyr4",

 ],

  buddha: [

    "IMGL7139-2_evavfp",
    "IMGL4531-3_k8c0ic",
    "633A2876-2_pw4zfk",
    "IMGL4515_o9oxem",
    "IMGL4558-2_otc0nt",
    "633A2819-2_t9iwkw",
    "633A2823_yvxnef",
    "IMGL1050_wtdpdc",
  


 ],

 drawings: [
  "IMG_6974_kbmdgm",
  "IMG_8584_ypf9pv",
  "IMG_8082_sdchva",
  "IMG_7965_2_upnqew",
  "IMG_6964_as8q33",
  "IMG_7777_zgfkc8",
  "IMG_6974_kbmdgm",
  "IMG_6975_hk4zfe",
  "IMG_6986_qvqsra",
  "IMG_6950_noes5e",
  "IMG_6956_wf7x7t",
  "IMG_6982_gzfvoq",
  "IMG_6954_dm40bc",
  "IMG_6955_orrheb",
  "IMG_6937_2_g3li7p",
  "IMG_8748_no2eyf",
  "IMG_7805_kx9ojh",
  "IMG_8499_uxedsg",
  "IMG_8077_qhzuhd",
  "IMG_8698_epbugi",
  "IMG_7965_twozgt",
  "IMG_7779_ipd4hb",
  "IMG_6973_2_qfaq5j",


 ],
 me: [
  
 "IMGL1262-2_vperob",

 ],
 people: [
  
 "IMGL1262-2_vperob",
 "IMGL1628_u4vdqg",
 "IMGL1472-2-2_wsn4re",
 "IMGL8510-2_v0uikr",

 "IMGL2047_oao8kz",
 "IMGL6026_djlq7e",
 "IMGL1615_xmmjsw",
 "IMGL2031_vstfhy",
 "IMGL6026_djlq7e",
 "IMGL1604_hrpilr",
 "IMGL1717_olhddz",
 "IMGL8521_lfgizy",
 "IMGL1692-2_hapvaf",
 "IMGL2015_s0crl8",
 "IMGL1452_zmyamn",
 "IMGL1805_ylvhnc",
 "IMGL1976_dpmdj0",
 "IMGL1633_epxolu",
 "IMGL1578_wkwxt1",
 "IMGL1574-3_v9zama",
 "IMGL1595_znvmkr",
 "IMGL1783_joijri",
 "IMGL1494-2_m9wi7u",
 "IMGL2015_s0crl8",

 ],

};
