const CLOUD = "https://res.cloudinary.com/dhbmaw1bm/image/upload/w_2500,q_auto,f_auto";
// const CLOUD = "https://res.cloudinary.com/dhbmaw1bm/image/upload";
const CLOUD_THUMB = "https://res.cloudinary.com/dhbmaw1bm/image/upload/w_800,q_auto,f_auto";



const photos = {
  nippon: [
    { id: "IMGL9507-2_v7b1qi", alt: "Temple japonais sous la neige, Kyoto" },
    "IMGL9507-2_v7b1qi",
    "IMGL9125_xi2v8p",
    "IMGL9022-2_rkc5iz",
    "IMGL9290_qkl7ms",
    "IMGL9455-2_k2gf4n",
    "IMGL8016_abso7v",
    "IMGL7076_bvbf8d",
    "IMGL7079-2_wygdzy",
    "IMGL7085-2_vslaft",
    "IMGL7133-2_mwzhwz",
    "IMGL6308_m3wdzf",
    "IMGL6361-2_impjst",
    "IMGL6308_m3wdzf",
    "IMGL6401_t0sgu3",
    "IMGL6361_o04q0l",
    "IMGL6361_o04q0l",
    "IMGL6308-2_dfy8bp",
    "633A6188_fc5h7j",
    "633A5834_qxhjbb",
    "633A5836_l1cr8y",
    "633A5935-2_r1itex",
    "633A5342-2_oyh2vn",
    "633A5350_mnpc5c",
    "633A3955_fbaer4",
    "633A2655_rjyv6d",
    "633A4353_rvbrzi",
    "633A2100_zv9vi1",
    "633A2315_sylxvg",
    "633A2332_tieznu",
    "633A2670_lifeof",
    "633A2647_da8bf9",
    "v1767280805/IMGL1205_ekhgm3.jpg",
    { id: "633A2876-2_ijjdyz", alt: "Statue of a Buddha holding a staff under cloudy skies", description: "A serene photo of a Buddha statue holding a staff, silhouetted against a dramatic stormy sky. This image captures the essence of Japanese spirituality and architecture." },
    "633A2291_kzpht8",
    "633A2332_tieznu",
    "633A2670_lifeof",
    "633A2633_hsprzi",
    { id: "633A2947-3_ipnlh1", alt: "Kyoto temple amidst urban streets with tangled wires", description: "Explore the unique blend of ancient Japanese architecture and modern urban life in this stunning street photograph capturing a Kyoto temple surrounded by cluttered electrical lines." },
    { id: "633A2948_dbigqw", alt: "Kyoto street scene with pagoda and tangled wires", description: "Explore the charming streets of Kyoto with this stunning photo capturing a pagoda amidst tangled electrical wires, showcasing the city's unique blend of tradition and modernity." },
    { id: "633A2823_yi1gyn", alt: "Kyoto temple steps with autumn foliage and pagoda architecture", description: "Explore the tranquil beauty of Kyoto's ancient temples during autumn. Experience the stunning contrast between stone steps, vibrant red leaves, and traditional Japanese architecture." },
    "633A2801-2_ehmumd",
    "633A2791_nrly1v",
    "633A2742_hbcanb",
    "633A2678_gdmuxc",
    "633A9782_snev9q",
    "633A9750-2_v9yu1p",
    "633A9737_htbmdo",
    "633A9774_lncvuz",
    "IMGL7139-2_evavfp", //buddha//

   
  ],
  city: [
  { id: "street_art_mural_fish_flowers", alt: "street mural featuring fish and flowers on a building facade", description: "Explore the vibrant street art scene with this striking mural featuring fish and flowers on an urban building facade, capturing the essence of artistic expression in city life." },
  { id: "monorail_track_elevated", alt: "monorail train on elevated track against blue sky", description: "Explore the futuristic monorail train in this striking shot of a curved track against a bright, cloudless sky. A unique perspective captures the sleek design and vibrant colors of the train." },
  { id: "urban_mural_fish_wave", alt: "street mural featuring fish and waves on a building facade", description: "Explore the vibrant street art of an urban alley with this stunning mural of fish and waves, capturing the essence of city life." },
  { id: "osaka_food_signs_vintage", alt: "vibrant street scene with large food signage in Osaka", description: "Experience the lively atmosphere of Osaka's famous street scene featuring giant food signs and vintage-style architecture. A must-see for food lovers and photography enthusiasts alike." },
  { id: "osaka_mural_fish_floral", alt: "mural art on a building with fish and floral designs in Osaka", description: "Explore the vibrant street art of Osaka, featuring detailed murals like this striking fish and floral design. Don't miss these unique urban artworks during your visit to Japan." },
  { id: "graffiti_fish_mural", alt: "graffiti mural of fish on urban building facade", description: "Explore the vibrant street art scene with this striking mural of fish adorning a city wall, capturing urban creativity and artistic expression." },
  { id: "osaka_crab_sign_vivid", alt: "vibrant street scene with large crab sign in Osaka", description: "Explore the colorful streets of Osaka's Namba district with this stunning shot featuring a giant crab sign, capturing the lively atmosphere and local culture." },
  { id: "osaka_evening_streetscape", alt: "Osaka street scene with illuminated signs and a historic building at dusk", description: "Explore the vibrant streets of Osaka during golden hour. This shot captures the historic architecture, illuminated signs, and bustling atmosphere of this iconic Japanese city." },
  { id: "tokyo_skytree_cloudy", alt: "Tokyo Skytree in a cloudy urban setting", description: "Explore the iconic Tokyo Skytree from an urban angle. Discover the city's skyline and architecture under a cloudy sky." },
  { id: "neon_sumo_cityscape", alt: "vibrant neon-lit street scene with sumo wrestlers and Japanese lanterns", description: "Explore the lively atmosphere of a neon-lit street featuring sumo wrestlers and traditional Japanese lanterns, captured in this vibrant cityscape image." },
  { id: "osaka_hips_dusk", alt: "Osaka's iconic HIPS building at dusk with illuminated trees and traditional shops.", description: "Experience the vibrant cityscape of Osaka at dusk. This striking shot captures the HIPS building, surrounded by traditional shops and illuminated autumn trees." },
  { id: "urban_futuristic_bridge", alt: "Modern urban bridge with futuristic art installation against city skyline", description: "Explore the sleek modernity of this bridge adorned by a unique art installation set against the backdrop of a bustling city skyline. Experience urban architecture and contemporary art seamlessly intertwined." },
  { id: "tokyo_skytree_urban_2", alt: "Tokyo Skytree framed by urban wires and buildings", description: "Explore the iconic Tokyo Skytree through a unique urban lens, capturing its towering presence amidst city wires and brick buildings. A must-see for travel photography enthusiasts." },
  { id: "kyoto_red_lanterns", alt: "traditional Japanese restaurant with red lanterns and striped awning", description: "Explore the vibrant atmosphere of a classic Japanese eatery adorned with striking red lanterns, captured from an intriguing street-level angle." },
  { id: "modern_skyscraper_day", alt: "modern skyscraper with intricate facade against a bright sky", description: "Explore the striking modern architecture of this urban landmark under clear skies. Discover unique angles and details that make it stand out." },
  { id: "tsutenkaku_dusk", alt: "Tsutenkaku Tower in Osaka at dusk", description: "Explore the vibrant cityscape of Osaka with stunning shots of Tsutenkaku Tower at dusk. Experience Japan's iconic landmark up close." },
  { id: "kyoto_red_pagoda_power_lines", alt: "Kyoto street scene with pagoda and tangled power lines", description: "Explore the charming streets of Kyoto with this stunning photo capturing a red pagoda amidst power lines and traditional architecture. Perfect for travel enthusiasts and architecture lovers." },
  { id: "building_with_circular_tower", alt: "Modern building with circular tower and reflective facade", description: "Explore the unique architectural beauty of a modern building with its distinctive circular tower and sleek reflective facade. This striking shot captures the essence of contemporary urban design." },
  { id: "osaka_namba_festival", alt: "colorful street festival with large statues and lanterns in Osaka", description: "Explore the vibrant streets of Osaka during a festive event. Colorful statues, traditional lanterns, and lively atmosphere make this photo unique." },
  { id: "kyoto_nishiki_octopus", alt: "Kyoto's famous octopus statue at Nishiki Market", description: "Explore the vibrant atmosphere of Kyoto's Nishiki Market with this striking photograph featuring its iconic octopus statue. A must-see for travelers and food enthusiasts." },
  { id: "rusty_overhead_bridge", alt: "overhead bridge with rusty stairs and urban buildings in background", description: "Explore the gritty beauty of an urban landscape featuring a weathered overhead bridge with rust-stained stairs, surrounded by modern high-rise buildings. This striking shot captures the essence of industrial architecture blending seamlessly into contemporary cityscapes." },
  { id: "narita_temple_streets", alt: "Narita Temple, Japan - street view with pagoda and traditional architecture", description: "Explore the serene streets of Narita, Japan, featuring its iconic pagoda and traditional Japanese architecture. A must-see for travelers interested in Asian culture and temple photography." },
  { id: "japanese_street_lanterns", alt: "colorful street scene with red lanterns and octopus statue in Japan", description: "Explore the vibrant streets of Japan with this stunning travel photograph featuring colorful red lanterns, an octopus statue, and traditional architecture. Perfect for travelers interested in Japanese culture and urban landscapes." },
  { id: "osaka_castle_moat", alt: "Osaka castle moat with modern skyscrapers in background", description: "Explore the historic Osaka Castle Moat surrounded by sleek modern skyscrapers, capturing a unique blend of old and new architecture." },
  { id: "osaka_ferris_wheel_day", alt: "Brightly colored ferris wheel and street scene in Osaka", description: "Explore the vibrant streets of Osaka with this stunning ferris wheel street photography. Capture the essence of Japan's bustling city life." },
  { id: "tokyo_skytree_dusk", alt: "Tokyo Skytree against a cloudy sky", description: "Explore the iconic Tokyo Skytree with this stunning dusk shot capturing its towering silhouette against a moody, overcast sky. A must-see for any traveler interested in Japanese architecture and cityscapes." },
  { id: "tokyo_skytree_cloudy_2", alt: "Tokyo Skytree against a cloudy sky", description: "Explore the iconic Tokyo Skytree with this dramatic shot of its towering structure under a cloudy sky. A must-see for any traveler visiting Japan." },
  { id: "osaka_ferriswheel_day", alt: "famous Osaka Ferris wheel and colorful street scene", description: "Explore the vibrant cityscape of Osaka with this stunning shot featuring the iconic Ferris wheel and lively street life." },
  { id: "futuristic_architecture_day", alt: "Futuristic building with spherical structure and train passing by", description: "Explore the unique architecture of a futuristic building featuring a spherical structure and passing train, captured from an urban angle." },
  { id: "industrial_crane_silhouette", alt: "Silhouetted cranes against a cloudy sky in an industrial port setting.", description: "Explore dramatic industrial port scenes with towering cranes silhouetted by a brooding, cloud-filled sky. Perfect for travel photography enthusiasts seeking unique urban landscapes." },
  { id: "industrial_cranes_dusk", alt: "industrial cranes against a cloudy sky at dusk", description: "Explore the industrial beauty of these towering cranes silhouetted against a dramatic, cloudy sky. Discover more unique travel and architecture photos by Thomas Ashtar." },
  { id: "odaiba_ferris_wheel_sunset", alt: "Red Ferris wheel amidst urban skyline at sunset", description: "Explore the vibrant cityscape with a striking red Ferris wheel against a golden hour sky. A must-see for photography enthusiasts and urban explorers." },
  { id: "doraemon_building_urban", alt: "Tall building with colorful Doraemon graphics on facade in urban setting", description: "Explore the vibrant street scene featuring a tall building adorned with iconic Doraemon graphics, capturing the essence of urban life and pop culture in Japan." },
  { id: "tokyo_shopping_arcade", alt: "Tokyo street scene with Torii gate and shopping arcade", description: "Explore the vibrant streets of Tokyo where a traditional Torii gate meets modern urban life in this stunning street photography shot." },
  { id: "tokyo_futurama_building", alt: "futuristic building with spherical structure in urban setting", description: "Explore the iconic Futurama Building in Tokyo, Japan. Unique architectural design featuring a spherical tower and modern cityscape views." },
  { id: "osaka_namba_octopus_2", alt: "famous octopus sign at Namba in Osaka, Japan", description: "Explore the iconic Namba Octopus Sign in Osaka, Japan. This vibrant street photography captures a unique landmark that's perfect for travelers and photographers alike." },
  { id: "curved_facade_architecture", alt: "Modern architecture with a curved facade and glass windows against an overcast sky.", description: "Explore the unique architectural beauty of this modern building with its distinctive curved facade under an overcast sky, perfect for photography enthusiasts seeking striking urban landscapes." },
  { id: "tokyo_skytree_overcast", alt: "Tokyo Skytree against overcast sky", description: "Explore the iconic Tokyo Skytree under a moody, cloudy sky. A stunning architectural marvel captured from an urban angle." },
  { id: "tokyo_asakusa_hips_tower_sunset", alt: "Asakusa Hips Tower in Tokyo at sunset", description: "Explore the iconic Asakusa Hips Tower in Tokyo captured during a stunning sunset. This unique architectural landmark stands out with its distinctive shape and vibrant city backdrop." },
  { id: "tokyo_cityscape", alt: "A bustling cityscape with a prominent glass-covered structure and busy streets.", description: "Explore the vibrant urban landscape of Tokyo featuring its iconic glass-covered building, bustling streets, and dynamic city life. A must-see for travel photography enthusiasts!" },
  { id: "tsutenkaku_dusk_view", alt: "tsutenkaku tower at dusk in osaka", description: "Explore the iconic Tsutenkaku Tower in Osaka during a stunning dusk. This unique angle captures its illuminated lights against a vibrant sky, perfect for travel enthusiasts and photographers alike." },
  { id: "osaka_ferris_wheel_sunset_2", alt: "famous Osaka Ferris wheel and Dotonbori canal in vibrant sunlight", description: "Explore the lively Dotonbori area of Osaka, Japan with stunning views of its iconic Ferris wheel and bustling canals bathed in golden sunset light." },
  { id: "kyoto_red_lanterns_octopus", alt: "A vibrant street corner in Japan with red lanterns and octopus statue", description: "Explore the lively streets of Japan, featuring a striking street corner adorned with red lanterns and an octopus statue. A must-see for travel photographers and culture enthusiasts." },
  { id: "urban_cityscape_bridge_2", alt: "Modern cityscape with pedestrian bridge and tall buildings", description: "Explore the vibrant urban landscape featuring a sleek pedestrian bridge amidst towering skyscrapers. This striking composition captures the essence of modern city life." },
  { id: "industrial_demolition", alt: "demolition of a large industrial structure with heavy machinery", description: "photograph captures the dramatic scene of an industrial building being demolished by heavy machinery under cloudy skies, ideal for travel photography enthusiasts and architectural fans." },
  { id: "osaka_ferris_wheel_sunset", alt: "Red Ferris wheel amidst urban skyline in Osaka", description: "Explore the vibrant city of Osaka with this stunning shot featuring a red Ferris wheel against a clear blue sky, captured during sunset." },
  { id: "giant_robot_odaiba", alt: "giant robot statue in front of modern building", description: "Explore the futuristic charm of Tokyo's Odaiba with this striking image of a giant robot statue standing tall against a modern skyline. A must-see for fans of anime and robotics." },
  { id: "tokyo_shrine_street", alt: "Tokyo street scene with Torii gate and shrine banners", description: "Explore the vibrant streets of Tokyo during the day. Discover a traditional Japanese shrine entrance adorned with colorful banners, perfect for travel photography enthusiasts." },
  { id: "japan_temple_wires", alt: "black and white temple amidst urban wires", description: "Explore the juxtaposition of traditional Japanese architecture with modern urban life in this striking black-and-white shot featuring a pagoda surrounded by electrical wires." },
  { id: "tokyo_skytree_urban", alt: "Tokyo Skytree against a cloudy sky with urban buildings and power lines.", description: "Explore the iconic Tokyo Skytree from an urban angle, showcasing its striking silhouette against a cloudy sky. Experience the contrast of modern architecture with classic city life." },
  { id: "tokyo_train_station", alt: "modern train station platform with overhead wires and urban backdrop", description: "Explore the sleek modernity of a Japanese train station, featuring clean lines, overhead wires, and an urban skyline. Capture the essence of contemporary urban life." },
  { id: "urban_murals_canal", alt: "vibrant street scene with colorful murals and canal in urban setting", description: "Explore the vibrant street scene featuring stunning murals along a canal, capturing the essence of a lively urban environment." },
  { id: "spherical_architecture_cloudy", alt: "Modern building with spherical structure against overcast sky", description: "Explore the unique architecture of a modern building featuring a prominent spherical structure set against an overcast sky, captured by Thomas Ashtar in his travel photography portfolio." },
  { id: "ferris_wheel_urban_dusk", alt: "Red Ferris wheel amidst urban skyline at dusk", description: "Explore the vibrant urban landscape with a striking red Ferris wheel as the centerpiece, captured during golden hour. A must-see for cityscape photography enthusiasts." },
  { id: "kyoto_pagoda_wires", alt: "Kyoto pagoda amidst urban architecture and tangled wires", description: "Explore the historic beauty of Kyoto's pagoda nestled between modern urban structures and a tangle of electrical wires, showcasing unique architectural details." },
  { id: "osaka_ferris_wheel_daytime", alt: "famous ferris wheel and colorful buildings in Osaka", description: "Explore the vibrant cityscape of Osaka with its iconic Ferris wheel and strikingly colorful architecture. A must-see for any traveler visiting Japan." },
  { id: "osaka_red_tower_sunset", alt: "Red observation tower amidst urban skyline at sunset", description: "Explore the vibrant Osaka skyline featuring the iconic red observation tower against a stunning sunset backdrop. This unique travel photograph captures the essence of modern Japanese architecture and urban beauty." },
  { id: "osaka_dotonbori_evening", alt: "vibrant street scene with neon signs and bowling alley in Osaka", description: "Explore the lively atmosphere of Osaka’s iconic entertainment district at dusk, featuring vibrant neon signs and a bowling alley landmark. A must-see for travelers exploring Japan's urban nightlife." },
  { id: "dotonbori_canal_ferriswheel", alt: "Osaka Dotonbori canal with Ferris wheel and vibrant street art", description: "Explore the lively streets of Osaka's Dotonbori with stunning views of its iconic Ferris wheel and colorful street art. A must-see for travelers in Japan." },
  { id: "construction_crane_dusk", alt: "construction cranes against a cloudy sky", description: "Explore the industrial beauty of construction cranes silhouetted against a dramatic sky during sunset." },
  { id: "tokyo_skytree_cloudscape", alt: "Tokyo Skytree against a cloudy sky", description: "Explore the iconic Tokyo Skytree from an unusual low angle, showcasing its unique architecture and dramatic cloud backdrop. A must-see for travel photography enthusiasts." },
   { id: "IMGL0052_kadhr6", alt: "Urban street scene with apartment building and sunset light", description: "Explore the urban beauty of an apartment building at sunset. This photo captures the essence of city life, blending architecture with natural lighting." },
   "IMGL0155_bbacvq",
   "IMGL0244_szszux",
   { id: "IMGL0110_sffxzc", alt: "vibrant neon signs and colorful decorations on a building in Osaka, Japan", description: "explore the lively streets of Osaka with this stunning photo featuring vibrant neon signs and colorful street art. perfect for travelers interested in urban landscapes and Japanese culture." },
   { id: "IMGL0053_ebnt2j", alt: "urban street scene under elevated train tracks at sunset", description: "Explore the vibrant urban landscape of a city captured during a stunning sunset, showcasing the interplay of light and shadow beneath an elevated train track." },
   { id: "IMGL0222-2_vyemrc", alt: "Vibrant street scene with neon signs and large golden statue in Osaka", description: "Explore the lively streets of Osaka at dusk, featuring vibrant neon signs and a striking golden statue. This unique travel photograph captures the essence of Japan's urban nightlife." },
   "IMGL0683_g6hobz",
   "IMGL0600_gq3rui",
   "633A4201-2_ccpn6k",
   { id: "633A0719-2_myeinr", alt: "Modern architecture with a curved tower against overcast sky", description: "Explore the striking modern architecture of this unique building under an overcast sky. Discover the distinctive architectural features and urban design in this captivating travel photograph." },
   { id: "633A1962_gghy9r", alt: "Kyoto riverbank with traditional Japanese houses and modern buildings in background", description: "Explore the serene beauty of Kyoto's riverbanks, where traditional Japanese architecture meets modern urban landscapes under a dusky sky. Capture this iconic scene for your travel photography portfolio." },
   "IMGL6869_loq8ks",
   { id: "IMGL2213-2_znhicb", alt: "pedestrian bridge over street in urban cityscape with modern architecture", description: "Explore the vibrant urban landscape featuring a pedestrian bridge and sleek modern architecture. A perfect blend of human activity and contemporary design." },
   { id: "IMGL0366_kiseoq", alt: "Tokyo train station platform with modern train and urban backdrop", description: "Explore the vibrant Tokyo train station platform with a sleek modern train and urban cityscape in this stunning travel photography shot." },
   { id: "633A0787-2_bfnm8s", alt: "overpass bridge with urban apartment buildings in background", description: "Explore the intricate architecture of an overpass bridge surrounded by modern urban apartment buildings. This unique shot captures the juxtaposition between industrial and residential cityscapes under a cloudy sky." },
   { id: "IMGL0022_ng44nl", alt: "Tokyo cityscape at dusk with large building and pedestrian bridge", description: "Explore the vibrant city of Tokyo at dusk from a unique angle, featuring a prominent building and pedestrian bridge. Captured by French photographer Thomas Ashtar on his Canon 5D Mark III." },
   { id: "IMGL6486_nm9ria", alt: "Red octopus sculpture on building facade", description: "Explore the vibrant red octopus sculpture adorning a building's exterior in this striking urban art piece. A must-see for photography enthusiasts and art lovers alike." },
   { id: "IMGL6479_gh4r3j", alt: "vibrant cityscape with colorful murals and canal in urban setting", description: "Explore the vibrant street art and bustling canal life at Namba in Osaka. This unique angle captures the lively spirit of Japan's entertainment district." },
   { id: "IMGL6508-2_ht6599", alt: "Brightly lit cityscape with large digital billboard and historic architecture at dusk.", description: "Explore the vibrant urban landscape of a historic city at dusk, featuring a large illuminated billboard and classic architectural details. Perfect for travel photography enthusiasts!" },
   { id: "IMGL0222-2_q6lsou", alt: "Vibrant street scene with neon signs and large golden statue in Osaka", description: "Explore the lively streets of Osaka at dusk, featuring vibrant neon signs and a striking golden statue. This unique travel photograph captures the essence of Japan's urban nightlife." },
   { id: "IMGL2289-3_yqhrcf", alt: "vibrant red octopus signboard in Namba district of Osaka", description: "Explore the iconic Namba octopus sign and street art in Osaka, Japan. This vibrant scene captures the lively atmosphere of this popular district." },
   { id: "IMGL0102_is13up", alt: "colorful street scene with large blue statue in Osaka, Japan", description: "Explore the vibrant streets of Osaka's Namba district featuring a striking blue statue and neon signs. Captured by Thomas (Ashtar 狐) on Canon 5D Mark III." },
   { id: "633A0668_zirvu8", alt: "giant robot statue in front of DiverCity Tokyo Plaza", description: "Explore the iconic giant robot statue at DiverCity Tokyo Plaza, a must-see attraction for anime and robotics enthusiasts. Experience its scale and intricate design up close!" },
   { id: "IMGL0106_znfah4", alt: "neon-lit street scene with colorful signs and traditional architecture", description: "Explore the neon-lit streets of Osaka at night. Vibrant signs and traditional architecture come alive under the blue sky." },
   "IMGL6734_hcar2g",
   { id: "633A4107_uu4baf", alt: "colorful street art on a building in Tokyo", description: "Explore the vibrant street art of Tokyo with this stunning photo capturing colorful murals and urban architecture." },
   { id: "IMGL0135_n59qbt", alt: "vibrant street scene with colorful neon signs and traditional Japanese architecture", description: "explore the lively atmosphere of a neon-lit street in Tokyo, capturing the vibrant energy of Japan's urban nightlife under a clear sky." },
   { id: "IMGL6503-5_idx04h", alt: "famous Osaka Dotonbori canal with Ferris wheel and colorful street art", description: "Explore the lively Osaka Dotonbori Canal, featuring a stunning Ferris wheel and vibrant street art under a dramatic sunset sky. A must-see for travelers in Japan!" },
   { id: "IMGL6479-2_d7wk4f", alt: "Colorful street scene with vibrant murals and canal in Osaka", description: "Explore the vibrant street art of Osaka's Namba district as the sun sets over its iconic canals. A must-see for travel photographers and art lovers." },
   { id: "IMGL2282_wdmhql", alt: "crowded street scene with neon signs in Japan", description: "Explore the vibrant nightlife of a Japanese city with stunning neon street photography. Capture the energy and culture of this bustling urban area." },
   { id: "IMGL0030_ffyepo", alt: "Tokyo cityscape at dusk with tram tracks and urban architecture", description: "Explore Tokyo's vibrant urban landscape from a unique angle, capturing the essence of its bustling streets at dusk." },
   { id: "IMGL6479_gh4r3j", alt: "vibrant cityscape with colorful murals and canal in urban setting", description: "Explore the vibrant street art and bustling canal life at Namba in Osaka. This unique angle captures the lively spirit of Japan's entertainment district." },
   { id: "633A0545-3_tbwbtu", alt: "Tokyo Metropolitan Government Building, architectural landmark", description: "Explore the futuristic architecture of Tokyo's iconic Metropolitan Government Building from a unique close-up angle. This photo captures the building's distinctive dome and modern design against an overcast sky." },
   { id: "IMGL0023_jls22d", alt: "urban cityscape with a prominent building and pedestrian bridge at dusk", description: "Explore the vibrant urban landscape of this city at dusk. Illuminated buildings, pedestrian bridges, and bustling streets come to life in this stunning travel photograph." },
  


  

  ],

  animals: [
   "IMGL9574_yyfs0p",
   "IMGL9573_jkhaxs",
   "IMGL9617-6_iirn6r",
   "IMGL9617-3_znzcpm",
   "IMGL9611-7_icvtgj",
   "IMGL1824-4_ff1nic",
   "IMGL1877-2_q2sw5t",
   "IMGL1874_ffzmwk",
   "IMGL1877-2_q2sw5t",
     "633A4646_pxyvi9",
    "633A4645_p2vyfe",
    "633A4851_ucuix0",
    "633A4773_koghen",
    "IMGL6576-2_zbyfji",
    "633A4052_cuq4jg",
    "633A0337_lzgtym",
    "633A0381-2_ojc6ke",
    "633A0355-3_kmm3qa",
    "IMGL0323_n4nfkw",
    "IMGL7735-2_t432k3",
    "IMGL7794-2_ok8p7s",
    "IMGL7686_mvc54s",
    "IMGL7735_ktld6j",
    "IMGL7803-2_tchn2m",
    "IMGL7721_ngwgda",
    "IMGL7696_l4bck2",
    "IMGL7687_gafpn0",
    "IMGL7697_ofxpom",
    "IMGL7720_zhmoz1",
    "IMGL7792-2_eycgbc",
    "633A4056_b6qkuo",
    "IMGL7735-2_t432k3",
    "633A0355-5_v9jirb",
    "633A4773_koghen",
    "IMGL0904_qcfgko",
    "MGL0899_kdca9a",
    "IMGL0058-2_fs8vii",
    "IMGL0717_rz16j9",
    "IMGL0058_f7wsy8",
    "IMGL0899-2_aukoso",
    "IMGL0173-2_krrrqt",
    "IMGL0720_p9tm35",
    { id: "IMGL0720_p9tm35", alt: "Heron, Kyoto" },
    "IMGL0222_evahkk",
    "IMGL0145-2-2_tx4r8d",
    "IMGL0760_nz9tav",


  

  ],

    blackwhite: [
    "v1767280805/IMGL1205_ekhgm3.jpg",
    "IMGL0084_ttuta6",
    "IMGL9617-7_qymeu0",
    "IMGL7785_shac7l",
    "IMGL6653_be7igj",
    "IMGL6648_pvlcjd",
    "IMGL6647_g29lkh",
    { id: "IMGL6508-3_ouclo0", alt: "black and white street scene with tall buildings and billboard advertisements", description: "Explore the vibrant cityscape of Osaka's Namba district in this striking black-and-white photo featuring towering billboards and bustling streets." },
    "633A4646_pxyvi9",
    "633A4645_p2vyfe",
    "633A4056_kxx1kr",
    { id: "633A2876-2_ijjdyz", alt: "Statue of a Buddha holding a staff under cloudy skies", description: "A serene photo of a Buddha statue holding a staff, silhouetted against a dramatic stormy sky. This image captures the essence of Japanese spirituality and architecture." },
    { id: "633A2819-2_phpifn", alt: "Kyoto temple under cloudy sky with pine trees", description: "Explore the serene beauty of a Kyoto temple captured in stunning black and white against a cloudy sky, framed by pine trees." },
    "633A9747_xc6jb3",
    "633A9668_dkksrt",
    "633A9668_dkksrt",
    "633A8526_hhzmsl",
    "633A8526_hhzmsl",
    "633A8262-2_om5rzu",
    "633A8255_fqbvfv",
    "633A8154_ggv7bg",
    "IMGL6671_slrzx3",
    "IMGL6649_hhaf0m",
    "IMGL9865-2_fplmno",
    "IMGL6734-2_yjuhti",
    "IMGL7687_gafpn0",
    "IMGL7697_ofxpom",
    "IMGL7792-2_eycgbc",
    "633A4056_b6qkuo",
    "IMGL7735-2_t432k3",
    "IMGL1615_xmmjsw",
    "IMGL1809_edjx8h",
    "IMGL2022_tpky3d",
    "IMGL2021_exwys6",
    "IMGL1687-4_l5ql0l",
    "IMGL1805_ylvhnc",
    "IMGL5907_enbs3m",
    "IMGL1574-3_v9zama",
    "IMGL1788-2_vgddv1",
    "IMGL0323_n4nfkw",


  

  ],

 rouge: [
  "IMGL7133-2_mwzhwz",
  "633A5342-2_oyh2vn",
  "IMGL7076_bvbf8d",
  "IMGL7079-2_wygdzy",
  "IMGL9125_xi2v8p",
  "IMGL6361-2_impjst",
  "633A9737_htbmdo",
  "IMGL9507-2_v7b1qi",
  "IMGL9290_qkl7ms",
  "633A6188_fc5h7j",
  "633A5834_qxhjbb",
  "IMGL6401_t0sgu3",
  "IMGL7034-4_axplpr",
  "633A5350_mnpc5c",
  "IMGL6794_bygzlw",
  "633A5935-2_r1itex",
  "633A0381-2_ojc6ke",
  "633A0337_lzgtym",
  "633A5350_mnpc5c",
  { id: "IMGL8467_luqxmg", alt: "Red torii gate in autumn foliage", description: "Explore the serene beauty of a Kyoto temple torii gate surrounded by vibrant fall foliage. Capture stunning travel photography with this iconic landmark." },
  { id: "IMGL9823_cra6rl", alt: "Bright red torii gate and bridge in autumnal setting", description: "Explore the vibrant colors of a Kyoto torii gate and bridge during fall, capturing serene Japanese architecture amidst lush foliage." },
  { id: "IMGL9709_zlasps", alt: "Traditional Japanese shrine gate with red and orange accents on a cloudy day", description: "Explore the serene beauty of a traditional Japanese shrine gate under a cloudy sky. This iconic red pagoda stands as a symbol of cultural heritage in Kyoto, Japan." },
  "IMGL6382-2_mm82yc",
 

 ],

 rose: [
  { id: "633A7585-3_rwbjox", alt: "Ferris wheel and roller coaster at an amusement park with a clear sky", description: "Explore the vibrant world of amusement parks! This image captures the iconic ferris wheel and thrilling roller coaster under a bright blue sky, perfect for thrill-seekers and families alike." },

 ],

 bleu: [
  { id: "sunburst_cloudscape", alt: "Sunbeams piercing through dramatic cloudscape with soft lighting", description: "Explore the beauty of a sunburst breaking through dense cloud cover in this stunning landscape photo. Perfect for nature and travel enthusiasts." },
  { id: "kyoto_sunset_autumn", alt: "Kyoto sunset over autumnal hills and traditional rooftops", description: "Experience the serene beauty of Kyoto at sunset with stunning views of autumn foliage and traditional Japanese rooftops. Capture the essence of Japan's cultural heritage in this breathtaking shot." },
  { id: "kyoto_sunset_dramatic", alt: "Sunbeams piercing through clouds over a mountainous landscape", description: "Capture the breathtaking view of Kyoto at sunrise with stunning sunbeams and clouds. Explore Japanese architecture in this travel photography portfolio." },
  { id: "ferris_wheel_amusement_park", alt: "ferris wheel and roller coaster under a blue sky", description: "Explore the thrill of an amusement park with this stunning shot featuring a towering ferris wheel and vibrant red roller coaster against a clear blue sky. Perfect for travel photography enthusiasts!" },
  { id: "castle_moat_sunset", alt: "Sunset reflection in moat at historical castle gate", description: "Explore the serene beauty of a historic castle's moat at sunset. Capture stunning reflections and architectural details." },
  { id: "sunset_over_japanese_architecture", alt: "serene sunset over traditional Japanese architecture and mountains", description: "Experience the tranquil beauty of a serene sunset overlooking traditional Japanese architecture and stunning mountain views. Capture this moment in your travel photography portfolio." },
  
 { id: "IMGL8169-2_hnin0q", alt: "Red and orange tower against deep blue sky", description: "Explore the vibrant red and orange hues of this striking architectural structure set against a stunning deep blue sky. A must-see for photography enthusiasts!" },
 { id: "IMGL3226_eyhiiz", alt: "Red pagoda temple in Kyoto under a clear blue sky", description: "Explore the serene beauty of Kyoto's iconic red pagoda temple, captured against a stunning clear blue sky. This stunning travel photography showcases traditional Japanese architecture and vibrant colors." },
 "633A2647_da8bf9",
 "633A2655_rjyv6d",
 { id: "IMGL2919_wva2bb", alt: "Kiyomizu-dera Temple in Kyoto, Japan", description: "Explore the serene beauty of the Kiyomizu-dera Temple in Kyoto, Japan. This stunning red pagoda stands majestically against a clear blue sky." },
 { id: "IMGL8067_e1tzwg", alt: "Kyoto's Kiyomizu-dera Temple against a clear blue sky", description: "Explore the stunning red and green rooflines of Kyoto's iconic Kiyomizu-dera Temple under a vibrant blue sky. Experience Japanese architecture at its finest!" },
 { id: "IMGL3061_qwqvlh", alt: "Kyoto's Kiyomizu-dera Temple under a clear blue sky", description: "Explore the stunning Kiyomizu-dera Temple, showcasing its iconic red pagoda against a vivid blue sky. Capture the essence of Japanese architecture and culture." },
 { id: "IMGL7265_ftcldl", alt: "Sunbeams through clouds over mountainous landscape", description: "Explore breathtaking sunbeams piercing through dramatic clouds over a stunning mountainous landscape. This unique travel photo captures the essence of nature's beauty." },
 { id: "IMGL6741_yi1yeo", alt: "Giant statue of Guanyin under a clear blue sky", description: "Explore the serene beauty of a giant Guanyin statue bathed in morning light, set against a clear blue sky. This stunning photograph captures the spiritual essence and architectural grandeur of this iconic landmark." },
 { id: "633A7585_tj66gm", alt: "ferris wheel and roller coaster against a blue sky", description: "Explore the thrill of an amusement park with this stunning shot featuring a Ferris wheel and roller coaster under a clear blue sky. Perfect for travel enthusiasts seeking adventure photography inspiration." },
 { id: "633A7552_e1mfnw", alt: "Ferris wheel against a cloudy sky with roller coaster in foreground", description: "Explore the vibrant amusement park scene featuring a giant Ferris wheel and roller coaster under a dramatic cloudy sky. A must-see for travel photography enthusiasts!" },
 { id: "IMGL7602_gwyged", alt: "Kyoto cityscape with autumn leaves and full moon", description: "Experience the serene beauty of Kyoto's cityscape at sunset. This stunning photo captures the vibrant autumn foliage, traditional architecture, and a full moon rising over the mountains." },
 { id: "IMGL7584_inet1k", alt: "Reflections in a moat at dusk with castle walls and trees", description: "Explore the serene beauty of a historic castle's moat at dusk, capturing reflections that mirror the dramatic sky. Discover more travel photography from Thomas (Ashtar Fox) across various locations." },
 { id: "633A7552-2_g3ijdg", alt: "Ferris wheel at an amusement park under a cloudy sky", description: "Explore the vibrant scene of a giant Ferris wheel against a dramatic cloudy sky in this stunning travel photograph." },
 { id: "633A7602_ucktyp", alt: "cosmo world ferris wheel at sunset", description: "Explore the vibrant Cosmo World Ferris Wheel in this stunning sunset travel photo. Capture the magic of this iconic landmark with our high-resolution images." },
 { id: "633A7171_phsgma", alt: "Traditional Japanese sake barrels with whale design", description: "Explore the intricate artistry of traditional Japanese sake barrels adorned with a striking whale design. This unique photo captures the cultural heritage and craftsmanship behind these iconic containers." },
 { id: "633A7585-3_rwbjox", alt: "Ferris wheel and roller coaster at an amusement park with a clear sky", description: "Explore the vibrant world of amusement parks! This image captures the iconic ferris wheel and thrilling roller coaster under a bright blue sky, perfect for thrill-seekers and families alike." },
 { id: "IMGL7265-2_zzx3qa", alt: "Dramatic cloudscape with sunbeams over a mountainous landscape", description: "Explore the breathtaking beauty of a mountainous region where sunlight pierces dramatic cloud formations, creating a stunning natural spectacle." },
 { id: "633A0588_endkhl", alt: "A giant Earth globe suspended in a modern building with glass walls and ceiling lights.", description: "Explore the stunning interior of a contemporary building featuring an enormous Earth globe hanging from the ceiling, perfect for travelers interested in architecture and unique design elements." },
 { id: "633A0588_endkhl", alt: "A giant Earth globe suspended in a modern building with glass walls and ceiling lights.", description: "Explore the stunning interior of a contemporary building featuring an enormous Earth globe hanging from the ceiling, perfect for travelers interested in architecture and unique design elements." },
{ id: "IMGL7596_pnsigi", alt: "serene temple complex at twilight with dramatic sky", description: "Explore the tranquil beauty of a temple complex at twilight, featuring stunning architecture and a majestic sky. Experience the serenity of this iconic location." },
"633A2670_xtiqs1",
"633A2633_nmlayg",
"633A2679_kg2d7p",
"633A2655_ri31ji",
"633A2540_x5ybgf",
"633A2581_tkrkwh",


 ],

 orange: [
  { id: "kiyomizu_dera_roof_2", alt: "Red pagoda roof against Kyoto cityscape under blue sky", description: "Explore the stunning red pagoda of Kiyomizu-dera temple, its vibrant colors contrasting with the serene backdrop of Kyoto's city skyline and clear winter skies." },
  { id: "torii_gate_autumn", alt: "Red torii gate framed by bare branches in Kyoto, Japan", description: "Explore the serene beauty of a red torii gate in Kyoto, Japan. Captured from an intriguing angle with bare tree branches framing the scene." },
  { id: "lighthouse_twilight", alt: "Red monument against a deep blue sky", description: "Explore the striking contrast of a vibrant red monument set against an inky-blue sky, capturing the essence of architectural beauty and dramatic lighting." },
  { id: "autumn_torii_shrine", alt: "A red torii gate leading to a traditional Japanese shrine surrounded by autumn foliage.", description: "Explore the serene beauty of an autumnal Japanese shrine, featuring a striking red torii gate and traditional architecture amidst vibrant fall colors. Perfect for travel photography enthusiasts." },
  { id: "japanese_temple_roof_2", alt: "Fushimi Inari Shrine's iconic red torii gates against a blue sky", description: "Explore the vibrant red torii gates of Fushimi Inari Shrine in Kyoto, Japan. This stunning photograph captures the spiritual beauty and architectural splendor of this iconic landmark." },
  { id: "japanese_pagoda_blue_sky", alt: "Kyoto's Kiyomizu-dera Temple Pagoda under a clear blue sky", description: "Explore the stunning architecture of Kyoto’s iconic Kiyomizu-dera Temple Pagoda, captured in breathtaking morning light against a vibrant blue sky. This photo is perfect for travelers seeking Japanese temple photography inspiration." },
  { id: "japanese_pavilion_red", alt: "Red pagoda in Kyoto temple complex under clear blue sky", description: "Explore the serene beauty of a red-roofed pagoda in Kyoto's ancient temple complex, captured on a crisp winter day with vibrant colors and stunning architecture." },
  { id: "japanese_shrine_red_torii", alt: "Red torii gate leading to a traditional Japanese shrine in autumn foliage.", description: "Explore the serene beauty of Kyoto's red torii gates amidst vibrant autumn leaves. This stunning travel photo captures the essence of Japan's ancient shrines and seasonal landscapes." },
  { id: "torii_gate_twilight", alt: "Red torii gate against a deep blue sky in Japan", description: "Explore the vibrant red torii gates of Kyoto, Japan. Captured from an unusual angle with dramatic lighting and deep blue skies." },
  { id: "pagoda_red_sky", alt: "Red pagoda against a vibrant blue sky in Kyoto", description: "Explore the stunning red pagoda of Kyoto, captured from an innovative angle under a vivid blue sky. This iconic Japanese landmark is a must-see for travelers and photography enthusiasts." },
  { id: "kiyomizu_dera_roof", alt: "Kyoto temple roof against a clear blue sky", description: "Explore the stunning contrast of Kyoto's iconic red temple roof set against a vibrant blue sky, capturing the essence of Japanese architecture in this serene cityscape." },
  { id: "kiyomizu_dera_pagoda_winter", alt: "Bright red pagoda against a clear blue sky in Kyoto.", description: "Explore the stunning red pagoda of Kyoto, Japan, captured under a vibrant blue sky. This iconic temple is a must-see for travelers and photography enthusiasts alike." },
  { id: "japanese_shrine_red_torii_3", alt: "Red torii gate and bridge over stream in Kyoto temple complex", description: "Explore the serene beauty of a famous Japanese temple featuring vibrant red torii gates, a stone bridge, and a tranquil stream. Perfect for travel photography enthusiasts." },
  { id: "traditional_temple_bright_sky", alt: "Traditional Japanese temple with vibrant red and green architecture against a clear blue sky.", description: "Explore the stunning architectural details of a Kyoto temple, featuring its iconic red pagoda set against a vivid blue sky. This photograph captures the serene beauty of traditional Japanese architecture." },
  { id: "pagoda_vivid_red", alt: "Bright red pagoda against a clear blue sky in Kyoto", description: "Explore the vibrant red roof of an iconic Kyoto pagoda under a stunning clear blue sky. This unique angle captures the essence of Japanese architecture and cultural beauty." },
  { id: "japan_torii_gate", alt: "Red torii gate leading to a Japanese shrine on a cloudy day.", description: "Explore the serene beauty of Kyoto's iconic red torii gate, captured under morning clouds. A must-see for travelers exploring Japan's temples and shrines." },
  { id: "japanese_shrine_red_torii_4", alt: "Kyoto temple with red torii gate and stone bridge", description: "Explore the serene beauty of Kyoto's iconic temples, featuring a striking red torii gate and traditional stone bridge. This picturesque scene captures the essence of Japanese architecture and tranquility." },
  { id: "kiyomizu_dera_pagoda_vibrant", alt: "Traditional Japanese temple roof against a clear blue sky", description: "Explore the serene beauty of Kyoto's iconic temples captured in stunning morning light. Experience the majesty and history of Japan’s ancient architecture." },
  { id: "japanese_pagoda_evening", alt: "Bright red pagoda against a clear blue sky, Kiyomizu-dera Temple in Kyoto", description: "Explore the iconic red pagoda of Kiyomizu-dera temple in Kyoto, Japan. Captured with dramatic lighting and stunning architecture." },
  { id: "pagoda_roof_details", alt: "Traditional Japanese temple architecture under a clear blue sky", description: "Explore the intricate roof details of Kyoto's iconic temples during winter, capturing the vibrant red and gold hues against a crisp blue sky." },
  { id: "kyoto_red_torii_sunset", alt: "Red torii gate overlooking Kyoto cityscape", description: "Explore the vibrant red torii gate of Kyoto's Fushimi Inari Shrine during a stunning sunset, capturing the iconic Japanese landmark in all its glory." },
  { id: "kiyomizu_dera_pagoda_10", alt: "Kyoto's Fushimi Inari Shrine under a clear blue sky", description: "Explore the vibrant red pagodas of Fushimi Inari Shrine in Kyoto, Japan. Capture stunning architecture against a brilliant blue sky." },
  { id: "red_pagoda_sky", alt: "Detailed view of a vibrant red pagoda against a clear blue sky.", description: "Explore the intricate details and vibrant colors of this iconic Kyoto pagoda under a clear blue sky, perfect for travel photography enthusiasts." },
  { id: "japanese_temple_roof", alt: "Red pagoda of Kiyomizu-dera Temple in Kyoto under a clear blue sky", description: "Explore the iconic red pagoda at Kiyomizu-dera Temple in Kyoto, Japan. Capture stunning architecture against a vibrant blue sky." },
  { id: "kiyomizu_dera_pagoda_11", alt: "Traditional Japanese temple architecture under a vibrant blue sky", description: "Explore the stunning red pagoda architecture of Kyoto, Japan. This captivating travel photo captures the intricate details and vibrant colors against a clear blue sky." },
  { id: "kiyomizu_dera_pagoda_2", alt: "Bright red pagoda under a clear blue sky", description: "Explore the vibrant beauty of Kyoto's iconic red pagoda against a stunning clear blue sky. Capture the essence of Japanese architecture in this stunning travel photography shot." },
  { id: "kiyomizu_dera_pagoda_autumn", alt: "Kyoto's Kiyomizu-dera Temple on a clear day", description: "Experience the vibrant colors and serene atmosphere of Kyoto’s iconic Kiyomizu-dera Temple captured during a stunning sunrise." },
  { id: "kiyomizu_dera_pagoda_4", alt: "Bright red pagoda against a blue sky in Kyoto", description: "Explore the vibrant beauty of Kyoto's iconic red pagoda set against a stunning blue sky, capturing its serene and majestic atmosphere." },
  { id: "kiyomizu_dera_pagoda_5", alt: "Bright red pagoda against a clear blue sky", description: "Experience the vibrant beauty of Kyoto's iconic red pagoda set against a stunning blue sky, capturing the essence of Japanese architecture and serene atmosphere." },
  { id: "kiyomizu_dera_pagoda_7", alt: "Bright red pagoda against a clear blue sky in Japan", description: "Explore the vibrant red pagoda of Kyoto, Japan, captured from an elevated angle under a brilliant blue sky. A stunning travel photography shot that highlights Japanese architecture." },
  { id: "kiyomizu_dera_pagoda_6", alt: "Brightly colored pagoda against a clear blue sky", description: "Explore the vibrant beauty of Kyoto's iconic pagoda under winter sunlight, capturing its intricate architecture and striking red hues." },
  
 "633A5834_qxhjbb", 
 "IMGL8016_abso7v",
 { id: "IMGL8169-2_hnin0q", alt: "Red and orange tower against deep blue sky", description: "Explore the vibrant red and orange hues of this striking architectural structure set against a stunning deep blue sky. A must-see for photography enthusiasts!" },
 { id: "IMGL3056_rj8gsi", alt: "Bright red pagoda against a clear blue sky", description: "Explore the stunning winter view of Kyoto's iconic Kiyomizu-dera temple, featuring its vibrant red pagoda and intricate architecture under a crisp blue sky." },
 { id: "IMGL8089_oefz9i", alt: "Vibrant orange pagoda against a clear blue sky", description: "Explore the stunning architecture of Kyoto's iconic temple, captured from a unique angle with vibrant orange roofs and a clear blue sky backdrop." },
 { id: "IMGL2981_cq2una", alt: "Kiyomizu-dera Temple in Kyoto, Japan", description: "Explore the iconic red pagoda of Kiyomizu-dera Temple in Kyoto, Japan. This stunning angle captures the vibrant architecture against a clear blue sky." },
 { id: "IMGL3061_qwqvlh", alt: "Kyoto's Kiyomizu-dera Temple under a clear blue sky", description: "Explore the stunning Kiyomizu-dera Temple, showcasing its iconic red pagoda against a vivid blue sky. Capture the essence of Japanese architecture and culture." },
 { id: "IMGL2981-2_efhcop", alt: "Bright red pagoda under a clear blue sky", description: "Explore the vibrant red pagoda of Kyoto's famous temple, captured from an unique angle against a crisp blue sky. A must-see for travel photography enthusiasts." },
 { id: "IMGL3226_eyhiiz", alt: "Red pagoda temple in Kyoto under a clear blue sky", description: "Explore the serene beauty of Kyoto's iconic red pagoda temple, captured against a stunning clear blue sky. This stunning travel photography showcases traditional Japanese architecture and vibrant colors." },
 { id: "IMGL2919_wva2bb", alt: "Kiyomizu-dera Temple in Kyoto, Japan", description: "Explore the serene beauty of the Kiyomizu-dera Temple in Kyoto, Japan. This stunning red pagoda stands majestically against a clear blue sky." },
 { id: "IMGL3231_mradbm", alt: "Bright red pagoda structure against a clear blue sky", description: "Explore the vibrant beauty of Kyoto's iconic red pagodas under a stunning blue sky. This photograph captures the essence of traditional Japanese architecture in its finest detail." },
 { id: "IMGL8067_e1tzwg", alt: "Kyoto's Kiyomizu-dera Temple against a clear blue sky", description: "Explore the stunning red and green rooflines of Kyoto's iconic Kiyomizu-dera Temple under a vibrant blue sky. Experience Japanese architecture at its finest!" },
 { id: "IMGL2942-4_yp62kf", alt: "Red pagoda of Kiyomizu-dera Temple in Kyoto under a clear blue sky", description: "Discover the stunning red pagoda at Kiyomizu-dera, Kyoto's iconic temple. Capture its vibrant hues and serene atmosphere." },
 "IMGL9413-2-3_xaon44",
 "IMGL9413-2-3_xaon44",
 { id: "IMGL9801_davkrw", alt: "A couple walks under an umbrella in front of a vibrant red pagoda temple on a cloudy day.", description: "Explore the serene beauty of Kyoto's iconic red pagoda temples with this stunning travel photography. Capture the essence of Japanese architecture and cultural heritage in one frame." },
 { id: "IMGL9801_davkrw", alt: "A couple walks under an umbrella in front of a vibrant red pagoda temple on a cloudy day.", description: "Explore the serene beauty of Kyoto's iconic red pagoda temples with this stunning travel photography. Capture the essence of Japanese architecture and cultural heritage in one frame." },
 { id: "IMGL9734_ztvbwg", alt: "Red torii gate and bridge at Fushimi Inari Shrine in Kyoto", description: "Explore the iconic red torii gates of Fushimi Inari Shrine, captured from a unique angle with dramatic lighting. A must-see for anyone visiting Japan's spiritual heart." },
 { id: "IMGL2813_p81pdx", alt: "Japanese temple with red pagoda and Japanese flag against a blue sky", description: "Explore the serene beauty of Kyoto's iconic temples, featuring vibrant red pagodas and the Japanese flag fluttering in the breeze." },
 { id: "IMGL9798_ubh1vs", alt: "Red torii gate and pagoda at Fushimi Inari Shrine in Kyoto", description: "Explore the iconic red torii gates of Fushimi Inari Shrine, a stunning temple complex in Kyoto, Japan. Capture the vibrant colors and serene atmosphere with your camera." },
 { id: "IMGL0547-2_asqlld", alt: "Red torii gate at Fushimi Inari Shrine in Kyoto, Japan", description: "Explore the iconic red torii gates of Fushimi Inari Shrine in Kyoto, Japan. Captured with precision and beauty by Ashtar Fox." },
 { id: "IMGL8454_dcgz6s", alt: "Red torii gate and traditional Japanese temple in autumn foliage", description: "Explore the serene beauty of a Kyoto temple during autumn, featuring vibrant red torii gates and traditional architecture amidst golden foliage." },
 { id: "IMGL9823_cra6rl", alt: "Bright red torii gate and bridge in autumnal setting", description: "Explore the vibrant colors of a Kyoto torii gate and bridge during fall, capturing serene Japanese architecture amidst lush foliage." },
 { id: "IMGL2765_gei45w", alt: "Kyoto's Kiyomizu-dera Temple under a dramatic sky", description: "Explore the stunning red pagoda of Kiyomizu-dera temple in Kyoto, Japan. This iconic landmark is set against a backdrop of lush greenery and a dynamic blue sky with clouds." },
 

 ],
  
vert: [
  
 "633A4773_koghen",
 "633A2801-2_ehmumd",
 "633A8875-2_zzr88o",
 "633A8066_slrnfe",
 "633A5635_bxjnci",
 "633A5543_ww7k8e",
 "633A5540-2_wvro56",
 "633A7197_urzwqh",
 "633A5637_acebts",
 "633A8117_kwymyf",
 "633A7185_mgt0x5",
 "633A2771_lthfsz",
 "633A2791-2_rngryh",
 "633A2812_g3fo2u",
 "633A9371_brrzmw",
 "633A5571_d2uocd",
 "633A5572_iptyzp",
 "633A2801-2_o6r6m9",
 "633A8147_uxi4q7",
 "633A8151_n0xybu",



 ],
jaune: [
  "IMGL7139_jdirjl",
  "633A8955_hiefub",
  "633A4997_xezelb",
  "633A0563_g9uvgm",
  "IMGL7143_wb18ym",
  "IMGL6924_ydjow4",
  "IMGL7145_ra40lh",
  "IMGL0600_brdbbl",
  "IMGL7142_lchheg",
  "633A8544_mwwa8n",
  "IMGL6711_rifu1c",
  "IMGL6924_ydjow4",
  "IMGL0600_brdbbl",
  "633A0381-2_ojc6ke",
  
 



 ],
 bynight: [
  
"633A4201-2_ccpn6k",
"IMGL6391_fyjyxc",
"IMGL6233_ty24q5",
"IMGL6382-2_mm82yc",
"IMGL6302_r9rbyi",
"633A5312_oikwmo",
"IMGL6227-5_mgwxwc",
"633A0505_qmrxzk",
"IMGL0296_joeng5",
"IMGL6302-2_owzop7",
"633A0442_kvknxc",
"IMGL6229_c7x8hc",
"633A8435_rgwvrv",
"633A4198_x7ldor",
"IMGL0312_xqjqd3",
"633A4181_glesvk",
"633A0461-2_qxbyr4",

 ],

  buddha: [
  { id: "kyoto_temple_dusk", alt: "Kyoto temple with bare tree and dramatic sky", description: "Explore the serene beauty of Kyoto's ancient temples under a dramatic sunset. This stunning shot captures the intricate architecture against the backdrop of a barren winter tree." },
  { id: "great_buddha_kamakura_3", alt: "The Great Buddha of Kamakura statue in Japan", description: "Explore the tranquil beauty of the Great Buddha of Kamakura, a iconic landmark in Japan. This stunning black and white photograph captures its majestic presence under clear skies." },
  { id: "great_buddha_kamakura_2", alt: "Great Buddha of Kamakura statue in Japan", description: "Explore the serene beauty of the Great Buddha of Kamakura in Japan. This stunning black and white photo captures the majestic architecture and tranquil atmosphere." },
  { id: "kyoto_temple_roof", alt: "Kyoto temple with intricate roof details and autumn foliage", description: "Explore the serene beauty of a Kyoto temple's ornate roof amidst vibrant fall colors. Capture stunning architecture and seasonal scenery." },
  { id: "kamakura_buddha_statue_2", alt: "Great Buddha statue at Kamakura, Japan", description: "Explore the serene beauty of the Kamakura Great Buddha in Japan. This iconic landmark captures the essence of Japanese spirituality and architecture." },
  { id: "monk_statue_cloudy_sky", alt: "Statue of a monk holding a staff under cloudy skies at a temple", description: "Explore the serene beauty of this temple with a detailed view of its statue, captured against a moody, cloud-filled sky. Perfect for travel photography enthusiasts." },
  { id: "temple_statue_dusk", alt: "serene temple statue against dark sky", description: "Explore the tranquil beauty of a temple statue set against the darkening sky. This serene photograph captures the essence of ancient architecture and peaceful ambiance." },
  { id: "buddha_statue_black_white", alt: "black and white statue of Buddha in serene setting", description: "Explore the tranquil beauty of this iconic Buddha statue captured in stunning black and white. Experience the serenity of its surroundings with our travel photography portfolio." },
  { id: "kyoto_autumn_temple", alt: "Traditional Japanese temple with ornate roof and autumn foliage", description: "Explore the serene beauty of a Kyoto temple during autumn. Captured from an angle that highlights its intricate architectural details amidst vibrant fall colors." },
  { id: "kamakura_buddha_statue", alt: "Giant Buddha statue in Kamakura, Japan", description: "Explore the serene beauty of the Great Buddha at Kotoku-in Temple in Kamakura, Japan. Captured with stunning sepia tones and architectural details." },
  { id: "kyoto_temple_pine_trees", alt: "Kyoto temple with traditional architecture and pine trees", description: "Explore the serene beauty of a historic Japanese temple surrounded by ancient pines in Kyoto. Capture stunning architectural details and vibrant autumn colors." },
  { id: "great_buddha_kamakura", alt: "Great Buddha of Kamakura, Japan", description: "Explore the majestic Great Buddha of Kamakura in Japan. This iconic statue offers a stunning view and is perfect for travelers seeking cultural and architectural wonders." },
  { id: "kiyomizu_dera_autumn", alt: "Kyoto temple with autumn leaves and traditional architecture", description: "Explore the serene beauty of Kyoto's temples in fall colors. This image captures the essence of Japanese architecture during the autumn season, showcasing vibrant reds against a classic pagoda backdrop." },
  { id: "kamakura_buddha_bw", alt: "Black and white image of a large Buddha statue with intricate robes under a clear sky.", description: "Explore the serene beauty of this iconic black-and-white photo featuring a majestic Buddha statue, set against a clear blue sky. Ideal for travelers seeking spiritual and architectural inspiration in Japan's temples." },

    "IMGL7139-2_evavfp",
    { id: "IMGL4531-3_k8c0ic", alt: "giant seated Buddha statue in black and white", description: "Explore the serene beauty of a giant Buddha statue captured in stunning black and white. This iconic landmark is perfect for travel photography enthusiasts." },
    { id: "633A2876-2_pw4zfk", alt: "Statue of a Buddha holding a staff under cloudy skies", description: "A serene photo of a Buddha statue holding a staff, silhouetted against a dramatic stormy sky. This image captures the essence of Japanese spirituality and architecture." },
    { id: "IMGL4515_o9oxem", alt: "Great Buddha of Kamakura statue in Japan", description: "Experience the serene beauty of the Great Buddha of Kamakura at sunset. This iconic statue is a must-see for any traveler exploring the Japanese countryside." },
    { id: "IMGL4558-2_otc0nt", alt: "Buddha statue with serene expression and ornate headpiece", description: "Explore the tranquil beauty of a Buddha statue's serene expression captured in this stunning travel photograph. Discover more unique architectural details from around the world." },
    { id: "633A2819-2_t9iwkw", alt: "Kyoto temple under cloudy sky with pine trees", description: "Explore the serene beauty of a Kyoto temple captured in stunning black and white against a cloudy sky, framed by pine trees." },
    { id: "633A2823_yvxnef", alt: "Kyoto temple steps with autumn foliage and pagoda architecture", description: "Explore the tranquil beauty of Kyoto's ancient temples during autumn. Experience the stunning contrast between stone steps, vibrant red leaves, and traditional Japanese architecture." },
    { id: "IMGL1050_wtdpdc", alt: "moss-covered statue of a smiling monk in autumn foliage", description: "Discover the serene beauty of an ancient moss-covered monk statue amidst vibrant autumn leaves. Explore this picturesque scene with travel photographer Thomas Ashtar." },
  


 ],

 drawings: [
  "IMG_6974_kbmdgm",
  "IMG_8584_ypf9pv",
  "IMG_8082_sdchva",
  "IMG_7965_2_upnqew",
  "IMG_6964_as8q33",
  "IMG_7777_zgfkc8",
  "IMG_6974_kbmdgm",
  "IMG_6975_hk4zfe",
  "IMG_6986_qvqsra",
  "IMG_6950_noes5e",
  "IMG_6956_wf7x7t",
  "IMG_6982_gzfvoq",
  "IMG_6954_dm40bc",
  "IMG_6955_orrheb",
  "IMG_6937_2_g3li7p",
  "IMG_8748_no2eyf",
  "IMG_7805_kx9ojh",
  "IMG_8499_uxedsg",
  "IMG_8077_qhzuhd",
  "IMG_8698_epbugi",
  "IMG_7965_twozgt",
  "IMG_7779_ipd4hb",
  "IMG_6973_2_qfaq5j",


 ],
 me: [
  
 "IMGL1262-2_vperob",

 ],
 people: [
  
 "IMGL1262-2_vperob",
 "IMGL1628_u4vdqg",
 "IMGL1472-2-2_wsn4re",
 "IMGL8510-2_v0uikr",

 "IMGL2047_oao8kz",
 "IMGL6026_djlq7e",
 "IMGL1615_xmmjsw",
 "IMGL2031_vstfhy",
 "IMGL6026_djlq7e",
 "IMGL1604_hrpilr",
 "IMGL1717_olhddz",
 "IMGL8521_lfgizy",
 "IMGL1692-2_hapvaf",
 "IMGL2015_s0crl8",
 "IMGL1452_zmyamn",
 "IMGL1805_ylvhnc",
 "IMGL1976_dpmdj0",
 "IMGL1633_epxolu",
 "IMGL1578_wkwxt1",
 "IMGL1574-3_v9zama",
 "IMGL1595_znvmkr",
 "IMGL1783_joijri",
 "IMGL1494-2_m9wi7u",
 "IMGL2015_s0crl8",

 ],

};
